<?php	
	define("DB_SERVER","localhost");
	define("DB_USER","michele");
	define("DB_PASS","myknysna");
	define("DB_NAME","chickencentral");		
	define("FS_PATH","/home/michele/WebSites/public_html/chickencentral/public/PicturePlace/");
	define("PICTURE_ROOT","/PicturePlace/");
	define("DEFAULT_IMAGE","/assets/shutterstock_649522099.jpg");
?>